-- Add a short human-readable booking number
-- Format: QR-YYYYMMDD-XXXX (generated by application)
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS booking_number TEXT UNIQUE;

CREATE INDEX IF NOT EXISTS idx_bookings_booking_number ON bookings (booking_number);
